config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :session_times
  resources :categories
  resources :news
  resources :comments, only: [:new, :create]
  resources :cinemas
  resources :film_sessions
  resources :places
  get 'home/index'
  get 'calendar', to: 'home#calendar'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'users/:id' => 'users#show', :as => :user
  resources :users, except: [:show]
  root 'home#index'
  get '/liqpay_payment' => 'payments#liqpay_payment'
  # get '*path' => redirect('/errors/not_found')
end

app/models/session_time.rb
class SessionTime < ActiveRecord::Base
  has_many :film_session_session_times
  has_many :film_sessions, through: :film_session_session_times
end

app/controllers/session_times_controller.rb
class SessionTimesController < ApplicationController
  before_action :set_session_time, only: [:show, :edit, :update, :destroy]

  # GET /session_times
  # GET /session_times.json
  def index
    @session_times = SessionTime.all
  end

  # GET /session_times/1
  # GET /session_times/1.json
  def show
  end

  # GET /session_times/new
  def new
    @session_time = SessionTime.new
  end

  # GET /session_times/1/edit
  def edit
  end

  # POST /session_times
  # POST /session_times.json
  def create
    @session_time = SessionTime.new(session_time_params)

    respond_to do |format|
      if @session_time.save
        format.html { redirect_to @session_time, notice: 'Session time was successfully created.' }
        format.json { render :show, status: :created, location: @session_time }
      else
        format.html { render :new }
        format.json { render json: @session_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /session_times/1
  # PATCH/PUT /session_times/1.json
  def update
    respond_to do |format|
      if @session_time.update(session_time_params)
        format.html { redirect_to @session_time, notice: 'Session time was successfully updated.' }
        format.json { render :show, status: :ok, location: @session_time }
      else
        format.html { render :edit }
        format.json { render json: @session_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /session_times/1
  # DELETE /session_times/1.json
  def destroy
    @session_time.destroy
    respond_to do |format|
      format.html { redirect_to session_times_url, notice: 'Session time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session_time
      @session_time = SessionTime.where(id: params[:id]).limit(1).first
      if !@session_time.present?
        redirect_to '/errors/not_found'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def session_time_params
      params.require(:session_time).permit(:session_time)
    end
end

app/views/session_times/_form.html.erb
<%= form_for(session_time) do |f| %>
  <% if session_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(session_time.errors.count, "error") %> prohibited this session_time from being saved:</h2>

      <ul>
      <% session_time.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Session time</label>
    <div class="col-md-10">
      <%= f.text_field :session_time, class:"form-control" %>
   </div>
 </div>


  <div class="form-group">
   <div class="col-md-10 col-md-offset-2">
     <%= link_to 'Back', root_path, class:"btn btn-raised btn-default" %>
     <%= f.submit class:"btn btn-raised btn-primary m20" %>
    </div>
  </div>
<% end %>

app/views/session_times/edit.html.erb
<div class="well bs-component">
<h1>Editing Session Time</h1>

<%= render 'form', :session_time => @session_time %>

<%= link_to 'Show', session_time %> |
<%= link_to 'Back', session_times_path %>
  </div>

app/views/session_times/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Session Times</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @session_times.each do |session_time| %>
      <tr>
        <td><%= session_time.session_time %></td>
        <td><%= link_to 'Show', session_time %></td>
        <td><%= link_to 'Edit', edit_session_time_path(session_time) %></td>
        <td><%= link_to 'Destroy', session_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Session time', new_session_time_path %>

app/views/session_times/new.html.erb
<div class="well bs-component">
<h1>New Session Time</h1>

<%= render 'form', :session_time => @session_time %>

<%= link_to 'Back', session_times_path %>
  </div>

app/views/session_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @session_time.session_time %>
</p>

<%= link_to 'Edit', edit_session_time_path(@session_time) %> |
<%= link_to 'Back', session_times_path %>