config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :session_times
  resources :categories
  resources :news
  resources :comments, only: [:new, :create]
  resources :cinemas
  resources :film_sessions
  resources :places
  get 'home/index'
  get 'calendar', to: 'home#calendar'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'users/:id' => 'users#show', :as => :user
  resources :users, except: [:show]
  root 'home#index'
  get '/liqpay_payment' => 'payments#liqpay_payment'
  # get '*path' => redirect('/errors/not_found')
end

app/models/film_session.rb
class FilmSession < ActiveRecord::Base
  has_many :comments, as: :commentable, :dependent => :destroy
	belongs_to :cinema
  has_many :film_session_session_times
  has_many :session_times, through: :film_session_session_times
  has_many :film_session_categories
  has_many :categories, through: :film_session_categories, :counter_cache => true
	has_many :places, :dependent => :destroy
  belongs_to :user
  validates :user_id, presence: true
  validates :session_name, presence: true
  validates :cinema_id, presence: true
  validates :number_of_session_place, presence: true
  validates :rating, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :trailer_link, presence: true
  validates :film_sessions_poster, presence: true

  has_attached_file :film_sessions_poster, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :film_sessions_poster, content_type: /\Aimage\/.*\Z/

  delegate :cinema_name, :to => :cinema, :prefix => true



  def self.search(search)
    if search
      where(["session_name LIKE ?","%#{search}%"])
    elsif
      all
    end
  end
  # accepts_nested_attributes_for :places, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/film_sessions_controller.rb
 class FilmSessionsController < ApplicationController
  before_action :delete_old_places, only: [:show]
  before_action :set_film_session, only: [ :show, :edit, :update, :destroy, :getBookingPlaces]
  before_action :check_if_admin, only: [:new, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]

  helper_method :find_user_comment_id

  def index
    check_search_params
    @film_sessions = @film_sessions.includes(:places)
    @film_sessions = @film_sessions.includes(:categories)
  end

  def show
    #create params for comments
    session[:id] = @film_session.id
    session[:type] = "FilmSession"
    #Get params from calendar
    @session_time = params[:session_time]
    @session_day = params[:day]
    get_list_of_session_times
    check_session_params
    get_comments
    places_functional
    check_booking_time
  end

  def new
    @film_session = FilmSession.new
  end

  def edit
  end

  def create
    @film_session = current_user.film_sessions.build(film_session_params)
    if @film_session.save
      flash[:success] = "New film session was successufly created"
      redirect_to calendar_path
    else
      render 'new'
    end
  end

  def update
    if @film_session.update(film_session_params)
      flash[:success] = "Film session was successufly updated"
      redirect_to film_session_path(@film_session)
    else
      render 'new'
    end
  end

  def destroy
    @film_session.destroy
    flash[:danger] = "Film session was successufly deleted"
    redirect_to film_sessions_path
  end

  private

    def check_search_params
      if params[:search].nil?
        @film_sessions = FilmSession.all
      else
        @film_sessions = FilmSession.search(params[:search])
      end
    end

    def find_user_comment_id(comment)
      user_comment = User.find(id = comment.user_id )
    end

    def check_session_params
      if !@times_presence || @session_time == nil || @session_day == nil || @session_day  < Date.today.to_s || @session_day > @film_session.session_end_date
         flash[:danger] = "Sessions with such parameters do not exist"
         return redirect_to calendar_url
      end
    end

    def get_list_of_session_times
      if @film_session.session_times.where(session_time: @session_time).empty?
        @times_presence = false
      else
        @times_presence = true
      end
    end

    def get_comments
      @comments = Comment.where(commentable_id: @film_session.id).order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    end

    def places_functional
      @t = Time.now
      @booked_places = @film_session.places
      @test = getBookingPlaces
      @array_of_places = params[:data_value] || []
      @array_length = params[:array_length]
      if @array_of_places != []
        render "form_for_places", :layout => false
      end
    end

    def delete_old_places
      @film_sessions_places = FilmSession.all
      @film_sessions_places.each do |film_session_place|
        film_session_place.places.each do |place|
          if Date.today.to_s > place.session_date
            place.delete
          end
        end
      end
    end

    def check_if_admin
      if !user_signed_in? || !current_user.admin?
        flash[:danger] = "You have't access rights for this operation"
        redirect_to root_path
      end
    end

    def set_film_session
      @film_session = FilmSession.where(id: params[:id]).limit(1).first
      if !@film_session.present?
        redirect_to '/errors/not_found'
      end
    end

    def getBookingPlaces
     @places = Place.all
     @placesBySession = @places.where(film_session_id: params[:id], session_time: @session_time, session_date: @session_day )
     @result = []
     for i in 0..@placesBySession.length-1
      @result.push(@placesBySession[i].place_number)
     end
     return @result
    end

    def film_session_params
      params.require(:film_session).permit(:session_start_date, :cinema_id, :session_name,
                                           :number_of_session_place, :user_id, :description,
                                           :rating, :trailer_link, :film_sessions_poster,
                                           :price, :session_end_date, category_ids: [],
                                           session_time_ids: [])
    end
end

app/views/film_sessions/_form.html.erb
<%= form_for film_session, validate: true do |f| %>
  <% if film_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film_session.errors.count, "error") %> prohibited this film_session from being saved:</h2>

      <ul>
      <% film_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="control-group">
    <%= f.label :cinema_id, class:"col-md-2 control-group" %>
    <div class="controls">
      <%= collection_select( :film_session, :cinema_id, Cinema.all, :id, :cinema_name, {}, { :multiple => false } ) %>
    </div>
  </div>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Session name</label>
    <div class="col-md-10">
      <%= f.text_field :session_name, class:"form-control" %>
   </div>
 </div>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Session start date</label>
    <div class="col-md-10">
      <%= f.text_field :session_start_date, class:"form-control datepicker" %>
   </div>
 </div>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Session end date</label>
    <div class="col-md-10">
      <%= f.text_field :session_end_date, class:"form-control datepicker" %>
   </div>
 </div>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Price</label>
    <div class="col-md-10">
      <%= f.number_field :price, class:"form-control" %>
   </div>
 </div>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Number of session place</label>
    <div class="col-md-10">
      <%= f.number_field :number_of_session_place, class:"form-control" %>
   </div>
 </div>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Description</label>
    <div class="col-md-10">
      <%= f.text_area :description, class:"form-control" %>
   </div>
 </div>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Trailer link</label>
    <div class="col-md-10">
      <%= f.text_field :trailer_link, class:"form-control" %>
   </div>
 </div>

 <div class="form-group is-empty">
    <label class="col-md-2 control-label">Rating</label>
    <div class="col-md-10">
      <%= f.number_field :rating, class:"form-control" %>
   </div>
 </div>

    <div class="form-group is-empty is-fileinput">
      <label class="col-md-2 control-label">Poster</label>
       <div class="col-md-10">
        <input type="text" class="form-control" placeholder="Browse...">
        <%= f.file_field :film_sessions_poster %>
      </div>
    <span class="material-input"></span></div>


  <div class="field">
    <div class="row">
      <div class="col-sm-offset-0 col-sm-8">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cd| %>
          <%= cd.label(class: "checkbox-inline input_checkbox") { cd.check_box(class: "checkbox") + cd.text } %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="row">
      <div class="col-sm-offset-0 col-sm-8">
        <%= f.collection_check_boxes :session_time_ids, SessionTime.all, :id, :session_time do |cd| %>
          <%= cd.label(class: "checkbox-inline input_checkbox") { cd.check_box(class: "checkbox") + cd.text } %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="form-group">
   <div class="col-md-10 col-md-offset-2">
     <%= link_to 'Back', film_sessions_path, class:"btn btn-raised btn-default" %>
     <%= f.submit class:"btn btn-raised btn-primary m20" %>
    </div>
  </div>

<% end %>

app/views/film_sessions/edit.html.erb
<div class="well bs-component">
  <h1>Editing Film Session</h1>

  <%= render 'form', :film_session => @film_session %>

  <%= link_to 'Show', @film_session %>
  <%= link_to 'Back', film_sessions_path %>
</div>

app/views/film_sessions/form_for_places.html.erb
<% if @array_of_places.present? %>
	<% @array_of_places.each do |n| %>
		<div class="col-md-6 booking_blocks" id="<%= n %>">
			<button class="close" id="close" value="<%= n %>">×</button>
			<div class="container">
				<div class="row">
					<%= form_for Place.new do |f| %>
						<%= render partial: "shared/place", locals: {f: f, n: n, film_session: @film_session} %>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>
	<div class="actions">
	    <%= submit_tag "Booking", :class => "btn btn-primary" %>
	</div>
<% end %>

app/views/film_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Film Sessions</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Cinema</th>
      <th>Session name</th>
      <th>Number of session place</th>
      <th>Session start date</th>
      <th>Session end date</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @film_sessions.each do |film_session| %>
      <tr>
        <td><p> <%= film_session.cinema_id %></p></td>
        <td><p> <%= film_session.session_name %></p></td>
        <td><p> <%= film_session.number_of_session_place %></p></td>
        <td><p> <%= film_session.session_start_date %></p></td>
        <td><p> <%= film_session.session_end_date %></p></td>
        <td><p> <%= film_session.rating %></p></td>
        <% if film_session.categories.any? %>
          <td><%= render film_session.categories %></td>
        <% end %>
        <% if user_signed_in? and current_user.admin? %>
          <td><%= link_to 'Edit', edit_film_session_path(film_session), class: "btn btn-raised btn-primary" %></td>
          <td><%= link_to 'Destroy', film_session, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-raised btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? and current_user.admin? %>
<%= link_to 'New Film session', new_film_session_path,class: "btn btn-primary btn-lg"  %>
<% end %>

app/views/film_sessions/new.html.erb
<div class="well bs-component">
  <h1>New Film Session</h1>

  <%= render 'form', :film_session => @film_session %>
  <%= link_to 'Back', categories_path %>

</div>

app/views/film_sessions/show.html.erb
<div class="well bs-component">
	<p id="notice"><%= notice %></p>
	<div class="well bs-component">
	    <div class="row">
	        <div class="col-md-4">
	            <!-- <%= image_tag @film_session.film_sessions_poster.url, class:"img-responsive"  %> -->
	            	<img src="https://www.kinopoisk.ru/images/film_big/822708.jpg" alt="" class="img-responsive">
	        </div>

	        <div class="col-md-8">
	            <h1><%= @film_session.session_name %></h1>
	            <p>Release: <b> <%= @film_session.session_start_date %> </b></p>
	            <p>Genre:
	                <% @film_session.categories.each do |category| %>
	                    <%= link_to category.name, category_path(category) %> |
	                <% end %>
	            </p>
	            <p> Ranking: <b><%= @film_session.rating %></b></p>
	            <p><%= @film_session.description %></p>
	            <p>Session time: <%= @session_time %></p>
							<p>Session day: <%= @session_day%></p>
	        </div>
	    </div>
	</div>
		<div class="clearfix"></div>
	<div class="well bs-component">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @film_session.trailer_link %>" frameborder="0" allowfullscreen></iframe>
	</div>
<div class="clearfix"></div>
	</div>
	<% if !user_signed_in? %>
		<h1 class="text-center">You should log in, for booking</h1>
	<% end %>
<div class="clearfix"></div>

		<% n = 0 %>
		<div class="places_block">
		<div class="test_hide hide">
			<a href="#data2" class="btn btn-raised btn-info group2" id="main-booking-btn group2" >Забронировать</a> <br />
		</div>
			<% @film_session.number_of_session_place.times do |session| %>
				 <% n = n + 1 %>
				 <% if @test.index(n) != nil %>
				 	<div class="btn btn-danger btn-raised place_block" id="place_<%= n %>">
						<p class="place_number">Місце № <%= n %></p>
						<div class="hidden-block hide">
							<p>Booked!</p>
						</div>
				 	</div>
				 <% else %>
				 	<div class="btn btn-info btn-raised place_block" id="place_<%= n %>" style="">
						<p class="place_number">Place № <%= n %></p>
						<% if user_signed_in? %>
						<div class="hidden-block">
							<a id="group" href="#data_<%= n %>">Booking</a>
						</div>
						<% end %>
						<div class="hidden">
							<div id="data_<%= n %>" class="<%= n %>">
								<%= form_for Place.new do |f| %>
									<%= render partial: "shared/place", locals: {f: f, n: n, film_session: @film_session} %>
								  <div class="actions">
								    <%= f.submit "Booking", :class => "btn btn-raised btn-primary" %>
								  </div>
								<% end %>
							</div>
						</div>
				 	</div>
				 <%end%>
			<% end %>
			<div class="hidden">
				<div id="data2">
					<% if @array_of_places.present? %>
						<% @array_of_places.each do %>
							<%= @array_of_places %>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
</div>
<div class="container">
	<div class="row">
		<% @comments.each do |comment| %>
			<div class="well bs-component comments">
				<div class="col-md-1">
  				<%= image_tag find_user_comment_id(comment).avatar.url, class:"img-responsive" %>
  				<br>
					<span><%= comment.created_at.to_date %></span>
					<br>
					<span><%= comment.user.login %></span>
				</div>
				<p><%= comment.body %></p>
				<div class="clearfix"></div>
			</div>
		<% end %>
	</div>
</div>
<div class="clearfix"></div>
	<div align="center">
		<%= will_paginate @comments %>
	</div>
	<% if user_signed_in? && current_user.login != nil %>
		<div class="container">
			<div class="row">
					<div class="well bs-component comments">
						<%= form_for Comment.new do |f| %>
							<div class="col-md-2">
	      				<%= image_tag current_user.avatar.url, class:"img-responsive" %>
								<p>Login: <%= current_user.login %></p>
							</div>
							<div class="form-group is-empty">
							   <label class="col-md-2 control-label">Comment:</label>
							   <div class="col-md-8">
							     <%= f.text_area :body, class:"form-control" %>
							  </div>
							</div>
							<%= f.hidden_field :commentable_id, :value => @film_session.id %>
							<%= f.hidden_field :commentable_type, :value => "FilmSession" %>
							<div class="form-group">
							 <div class="col-md-10 col-md-offset-2">
							   <%= link_to 'Back', film_sessions_path, class:"btn btn-raised btn-default" %>
							   <%= f.submit class:"btn btn-raised btn-primary m20" %>
							  </div>
							</div>
							<div class="clearfix"></div>
						<% end %>
						<div class="navi-btns">
						</div>
					</div>
				</div>
			</div>
	<% else %>
		<div class="well bs-component comments">
				<h2 class="text-warning text-center">To leave a comment, you need to be logged in and choose login in profile </h2>
			<div class="clearfix"></div>
		</div>
	<% end %>