config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :session_times
  resources :categories
  resources :news
  resources :comments, only: [:new, :create]
  resources :cinemas
  resources :film_sessions
  resources :places
  get 'home/index'
  get 'calendar', to: 'home#calendar'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'users/:id' => 'users#show', :as => :user
  resources :users, except: [:show]
  root 'home#index'
  get '/liqpay_payment' => 'payments#liqpay_payment'
  # get '*path' => redirect('/errors/not_found')
end

app/models/home.rb
# class Home < ActiveRecord::Base
#   def film_session_date_inspection
#     film_session.session_start_date == date.to_s || ( film_session.session_start_date < date.to_s and date.to_s <= film_session.session_end_date)
#   end
# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :inspect_film_session_date
  helper_method :find_session_time

  def index
    @film_session = FilmSession.last
    @news = News.order(:created_at).limit(2)
  end

  def calendar
    @film_sessions = FilmSession.all
    @film_sessions = @film_sessions.includes(:film_session_session_times)
    @date = params[:session_start_date] ? Date.parse(params[:session_start_date]) : Date.today
  end

  def inspect_film_session_date(date, film_session)
    film_session.session_start_date == date.to_s || ( film_session.session_start_date < date.to_s and date.to_s <= film_session.session_end_date )
  end

  def find_session_time(time)
    session_time = SessionTime.find(id = time.session_time_id).session_time
  end

  private

end

app/views/home/calendar.html.erb
<h1>Calendar</h1>
<div id="film_sessions">
  <h2 id="month">
    <%= link_to "<", session_start_date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", session_start_date: @date.next_month %>
  </h2>
  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @film_sessions %>
      <ul>
        <% @film_sessions.each do |film_session| %>
          <% if inspect_film_session_date(date,film_session) %>
            <% if date.to_s > Date.today.to_s %>
              <li>
                  <p><i class="fa fa-film" aria-hidden="true"></i> <%= film_session.session_name %></p>
                  <ul>
                    <% film_session.film_session_session_times.each do |time| %>
                      <li><i class="fa fa-clock-o" aria-hidden="true"></i> <%= link_to find_session_time(time), film_session_path(:session_time=>find_session_time(time),:day=>date, :id=>film_session.id) %></li>
                    <% end %>
                  </ul>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="well bs-component">
    <div class="row">
        <div class="col-md-4">
            <%= image_tag @film_session.film_sessions_poster.url, class:"img-responsive"  %>
        </div>

        <div class="col-md-8">
            <h1><%= @film_session.session_name %></h1>
            <p>Release: <b> <%= @film_session.session_start_date %> </b></p>
            <p>Genre:
                <% @film_session.categories.each do |category| %>
                    <%= link_to category.name, category_path(category) %>
                <% end %>
            </p>
            <p> Ranking: <b><%= @film_session.rating %></b></p>
            <p><%= @film_session.description %></p>
            <%= link_to "Choose session", calendar_path, class:"btn btn-raised btn-primary " %>
            <a class="various fancybox.iframe btn btn-raised btn-warning" href="https://www.youtube.com/embed/<%= @film_session.trailer_link %>" >Trailer</a>
        </div>
    </div>
</div>

<div class="well bs-component">
    <div class="row">
        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img class="img-responsive portfolio-item" src="http://nerdreactor.com/wp-content/uploads/2015/01/warcraft-film-500x300_c.jpeg?394dcb"  alt="">
            </a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img class="img-responsive portfolio-item" src="https://1.bp.blogspot.com/-DIQ6y8nV260/VuL-b0ysSPI/AAAAAAAAAJ0/dyWIyt7W73UlOEKA27jPSKp7o-DwLebDg/s1600/Captain-America-Civil-War-Official-Trailer-2-Hollywood-Movie-2016.jpg"  alt="">
            </a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img class="img-responsive portfolio-item" src="http://www.comicbookresources.com/imgsrv/imglib/500/300/1/apoca-social-f8cf0.jpg"  alt="">
            </a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img class="img-responsive portfolio-item" src="http://tiffanyyong.com/wp-content/uploads/2014/08/teenage-mutant-ninja-turtles-movie-poster-500x300.jpg"  alt="">
            </a>
        </div>
    </div>
</div>

<div class="well bs-component">
    <div class="row">
        <iframe width="auto" height="515" src="https://www.youtube.com/embed/<%= @film_session.trailer_link %>" frameborder="0" allowfullscreen></iframe>
    </div>
</div>

<div class="well bs-component">
    <div class="row">
        <div class="col-md-6 col-sm-12-col-xs-12 reklam_block_margin">
            <b><h2 class="text-muted">Don't be late,</h2></b>
            <b> <h1 class="text-warning">Book your ticket now!</h1></b>
            <h3 class="text-muted">Easy, simple & fast.</h3>
            <%= link_to '<i class="fa fa-ticket" aria-hidden="true"></i> Book ticket'.html_safe, calendar_path, class:"btn btn-raised btn-warning " %>

        </div>
        <div class="col-md-6 col-sm-12-col-xs-12 main_news_block">
            <h2 class="text-muted">News</h2>
            <hr>
            <% @news.each do |news| %>
                <div class="news_block">
                    <p class="news_title"><%= news.title %></p>
                    <p class="text-muted"><%= news.created_at.to_date %></p>
                    <p><%= news.description %></p>
                </div>
                <%= link_to "Read more", news_path(news), class:"btn btn-raised btn-primary " %>
                <hr>
            <% end %>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
   $(".various").fancybox({
      maxWidth : 800,
      maxHeight : 800,
      fitToView : false,
      width : '70%',
      height : '70%',
      autoSize : false,
      closeClick : false,
      openEffect : 'none',
      closeEffect : 'none'
   });
});
</script>