config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :session_times
  resources :categories
  resources :news
  resources :comments, only: [:new, :create]
  resources :cinemas
  resources :film_sessions
  resources :places
  get 'home/index'
  get 'calendar', to: 'home#calendar'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'users/:id' => 'users#show', :as => :user
  resources :users, except: [:show]
  root 'home#index'
  get '/liqpay_payment' => 'payments#liqpay_payment'
  # get '*path' => redirect('/errors/not_found')
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :film_session_categories
  has_many :film_sessions, through: :film_session_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category_film_sessions = @category.film_sessions
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.where(id: params[:id]).limit(1).first
      if !@category.present?
        redirect_to '/errors/not_found'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group is-empty">
      <label class="col-md-2 control-label">Name</label>
      <div class="col-md-10">
        <%= f.text_field :name, class:"form-control" %>
     </div>
   </div>

    <div class="form-group">
       <div class="col-md-10 col-md-offset-2">
         <%= link_to 'Back', cinemas_path, class:"btn btn-raised btn-default" %>
         <%= f.submit class:"btn btn-raised btn-primary m20" %>
      </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class="well bs-component">
  <h1>Editing Category</h1>

  <%= render 'form', :category => @category %>

  <%= link_to 'Show', @category %>
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><p><%= category.name %></p></td>
        <td><%= link_to 'Show', category, class: "btn btn-info" %></td>
        <% if user_signed_in? and current_user.admin? %>
          <td><%= link_to 'Edit', edit_category_path(category), class: "btn btn-primary" %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class:"btn btn-raised btn-primary" %>

app/views/categories/new.html.erb
<div class="well bs-component">
  <h1>New Category</h1>

  <%= render 'form', :category => @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Category: <%= @category.name %></h1>

  <% @category_film_sessions.each do |session| %>
  <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
    <header class="section__play-btn mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone mdl-color--teal-100 mdl-color-text--white">
      <%= image_tag session.film_sessions_poster.url(:medium) %>
    </header>
    <div class="mdl-card mdl-cell mdl-cell--9-col-desktop mdl-cell--6-col-tablet mdl-cell--4-col-phone">
      <div class="mdl-card__supporting-text">
        <h4><%= session.session_name %></h4>
        <%= session.description %>
      </div>
      <div class="mdl-card__actions">
           <%= link_to "Book Place", calendar_path, class:"btn btn-raised btn-warning" %>
        <% if user_signed_in? and current_user.admin? %>
          <%= link_to "Edit", edit_film_session_path(session), class:"btn btn-raised btn-primary" %>
        <% end %>
      </div>
    </div>
  </section>
  <div class="mt20"></div>
  <% end %>

  </div>
</div>